// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.normandy.first_run", false);
user_pref("app.normandy.migrationsApplied", 10);
user_pref("app.normandy.user_id", "d7fe94b6-1673-4b7d-a189-dd8b98bd7a70");
user_pref("app.shield.optoutstudies.enabled", false);
user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1632525082);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1632524427);
user_pref("app.update.lastUpdateTime.recipe-client-addon-run", 1632524523);
user_pref("app.update.lastUpdateTime.rs-experiment-loader-timer", 1632524933);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1632524547);
user_pref("app.update.lastUpdateTime.services-settings-poll-changes", 1632524962);
user_pref("app.update.lastUpdateTime.telemetry_modules_ping", 1632524457);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 0);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.cache.disk.amount_written", 19498);
user_pref("browser.cache.disk.capacity", 1048576);
user_pref("browser.cache.disk.filesystem_reported", 1);
user_pref("browser.contentblocking.category", "standard");
user_pref("browser.laterrun.bookkeeping.profileCreationTime", 1632524397);
user_pref("browser.laterrun.bookkeeping.sessionCount", 2);
user_pref("browser.laterrun.enabled", true);
user_pref("browser.migration.version", 96);
user_pref("browser.newtabpage.activity-stream.impressionId", "{2a73283e-c501-4813-8019-a829971aacdf}");
user_pref("browser.newtabpage.activity-stream.improvesearch.topSiteSearchShortcuts.havePinned", "yandex");
user_pref("browser.newtabpage.pinned", "[{\"url\":\"https://yandex.com\",\"label\":\"@яндекс\",\"searchTopSite\":true}]");
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pageActions.persistedActions", "{\"version\":1,\"ids\":[\"bookmark\",\"pinTab\",\"bookmarkSeparator\",\"copyURL\",\"emailLink\",\"addSearchEngine\",\"sendToDevice\",\"pocket\",\"screenshots_mozilla_org\"],\"idsInUrlbar\":[\"pocket\",\"bookmark\"]}");
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.policies.runOncePerModification.displayBookmarksToolbar", "false");
user_pref("browser.safebrowsing.provider.google4.lastupdatetime", "1632524416472");
user_pref("browser.safebrowsing.provider.google4.nextupdatetime", "1632526206472");
user_pref("browser.safebrowsing.provider.mozilla.lastupdatetime", "1632524399967");
user_pref("browser.safebrowsing.provider.mozilla.nextupdatetime", "1632545999967");
user_pref("browser.search.region", "BY");
user_pref("browser.search.useDBForOrder", true);
user_pref("browser.sessionstore.upgradeBackup.latestBuildID", "20210804193512");
user_pref("browser.slowStartup.averageTime", 947);
user_pref("browser.slowStartup.samples", 2);
user_pref("browser.startup.homepage_override.buildID", "20210804193512");
user_pref("browser.startup.homepage_override.mstone", "78.13.0");
user_pref("browser.startup.lastColdStartupCheck", 1632524932);
user_pref("browser.uiCustomization.state", "{\"placements\":{\"widget-overflow-fixed-list\":[],\"nav-bar\":[\"back-button\",\"forward-button\",\"stop-reload-button\",\"home-button\",\"customizableui-special-spring1\",\"urlbar-container\",\"customizableui-special-spring2\",\"downloads-button\",\"library-button\",\"sidebar-button\",\"fxa-toolbar-menu-button\"],\"toolbar-menubar\":[\"menubar-items\"],\"TabsToolbar\":[\"tabbrowser-tabs\",\"new-tab-button\",\"alltabs-button\"],\"PersonalToolbar\":[\"personal-bookmarks\"]},\"seen\":[\"developer-button\"],\"dirtyAreaCache\":[\"nav-bar\",\"toolbar-menubar\",\"TabsToolbar\",\"PersonalToolbar\"],\"currentVersion\":16,\"newElementCount\":2}");
user_pref("browser.urlbar.placeholderName", "Yandex");
user_pref("distribution.Kali.bookmarksProcessed", true);
user_pref("distribution.iniFile.exists.appversion", "78.13.0");
user_pref("distribution.iniFile.exists.value", true);
user_pref("doh-rollout.balrog-migration-done", true);
user_pref("dom.push.userAgentID", "caf77b13ef4544e89c4224a386ccafac");
user_pref("extensions.activeThemeID", "default-theme@mozilla.org");
user_pref("extensions.blocklist.pingCountVersion", 0);
user_pref("extensions.databaseSchema", 32);
user_pref("extensions.getAddons.cache.lastUpdate", 1632525083);
user_pref("extensions.getAddons.databaseSchema", 6);
user_pref("extensions.incognito.migrated", true);
user_pref("extensions.lastAppBuildId", "20210804193512");
user_pref("extensions.lastAppVersion", "78.13.0");
user_pref("extensions.lastPlatformVersion", "78.13.0");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.webcompat.perform_injections", true);
user_pref("extensions.webcompat.perform_ua_overrides", true);
user_pref("extensions.webextensions.ExtensionStorageIDB.migrated.doh-rollout@mozilla.org", true);
user_pref("extensions.webextensions.ExtensionStorageIDB.migrated.screenshots@mozilla.org", true);
user_pref("extensions.webextensions.uuids", "{\"doh-rollout@mozilla.org\":\"029e0a89-a2e7-4ff9-9b8c-3a513d17d47a\",\"formautofill@mozilla.org\":\"3942f480-277d-45a7-8288-66b035a05acc\",\"screenshots@mozilla.org\":\"f52fd400-6035-4f3a-87b7-71239f7f13cb\",\"webcompat-reporter@mozilla.org\":\"ffb1d08e-9273-46ea-bd76-08b17ba85224\",\"webcompat@mozilla.org\":\"17ede3a5-ffff-48c8-ad9e-b349a3395105\",\"default-theme@mozilla.org\":\"4322909a-1a7c-4b7c-9f30-5eb308ca5ebf\",\"google@search.mozilla.org\":\"fcb69220-6510-4312-bb65-fc871446a2ea\",\"amazondotcom@search.mozilla.org\":\"b3fd755a-b2fb-4c5e-995d-c856b5a25a9f\",\"wikipedia@search.mozilla.org\":\"6ebae936-49eb-4a02-bf4a-8ad5b49d7b6e\",\"bing@search.mozilla.org\":\"3cc926b0-ae36-4686-b9a2-35253c3ab120\",\"ddg@search.mozilla.org\":\"2d868e60-ef0e-405e-b9fc-e30d79575499\",\"yandex@search.mozilla.org\":\"6b3352ce-b1e3-45af-9f64-9053e03f11d3\"}");
user_pref("media.gmp-manager.buildID", "20210804193512");
user_pref("media.gmp-manager.lastCheck", 1632524531);
user_pref("media.gmp.storage.version.observed", 1);
user_pref("pdfjs.enabledCache.state", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("places.history.expiration.transient_current_max_pages", 112348);
user_pref("privacy.sanitize.pending", "[{\"id\":\"newtab-container\",\"itemsToClear\":[],\"options\":{}}]");
user_pref("security.remote_settings.crlite_filters.checked", 1632526314);
user_pref("security.remote_settings.intermediates.checked", 1632526314);
user_pref("security.sandbox.content.tempDirSuffix", "1982f5fa-7dc8-4af6-a702-6d0c96aff85e");
user_pref("security.sandbox.plugin.tempDirSuffix", "85563ad0-d789-45c7-8154-0b3e56ced222");
user_pref("services.blocklist.addons-mlbf.checked", 1632526324);
user_pref("services.blocklist.gfx.checked", 1632526324);
user_pref("services.blocklist.pinning.checked", 1632526314);
user_pref("services.blocklist.plugins.checked", 1632526324);
user_pref("services.settings.clock_skew_seconds", -1363);
user_pref("services.settings.last_etag", "\"1632517053196\"");
user_pref("services.settings.last_update_seconds", 1632526324);
user_pref("services.settings.main.anti-tracking-url-decoration.last_check", 1632526324);
user_pref("services.settings.main.cfr-fxa.last_check", 1632526324);
user_pref("services.settings.main.cfr.last_check", 1632526324);
user_pref("services.settings.main.fxmonitor-breaches.last_check", 1632526324);
user_pref("services.settings.main.hijack-blocklists.last_check", 1632526324);
user_pref("services.settings.main.language-dictionaries.last_check", 1632526324);
user_pref("services.settings.main.normandy-recipes-capabilities.last_check", 1632526324);
user_pref("services.settings.main.public-suffix-list.last_check", 1632526324);
user_pref("services.settings.main.search-config.last_check", 1632526324);
user_pref("services.settings.main.search-default-override-allowlist.last_check", 1632526324);
user_pref("services.settings.main.sites-classification.last_check", 1632526324);
user_pref("services.settings.main.url-classifier-skip-urls.last_check", 1632526324);
user_pref("services.settings.main.whats-new-panel.last_check", 1632526324);
user_pref("services.settings.security.onecrl.checked", 1632526314);
user_pref("signon.importedFromSqlite", true);
user_pref("toolkit.startup.last_success", 1632524931);
user_pref("toolkit.telemetry.cachedClientID", "c0ffeec0-ffee-c0ff-eec0-ffeec0ffeec0");
user_pref("toolkit.telemetry.previousBuildID", "20210804193512");
user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
